package Java;

public class Navbar {

    public String showNavbar(String nombre) {
        String usuario = "";
        if (nombre.equals("")) {

            usuario = " <nav class=\"navbar\" role=\"navigation\" aria-label=\"main navigation\">\n"
                    + "            <div class=\"navbar-brand\">\n"
                    + "                <a class=\"navbar-item\" href=\"/MicroTwitter/\">\n"
                    + "                    <img src=\"https://bulma.io/images/bulma-logo.png\" width=\"112\" height=\"28\">\n"
                    + "                </a>\n"
                    + "\n"
                    + "                <a role=\"button\" class=\"navbar-burger burger\" aria-label=\"menu\" aria-expanded=\"false\" data-target=\"navbarBasicExample\">\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                </a>\n"
                    + "            </div>\n"
                    + "\n"
                    + "            <div id=\"navbarBasicExample\" class=\"navbar-menu\">\n"
                    + "                <div class=\"navbar-start\">\n"
                    + "                    <a href=\"/MicroTwitter\" class=\"navbar-item\">\n"
                    + "                        Inicio\n"
                    + "                    </a>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div>\n"
                    + "\n"
                    + "                <div class=\"navbar-end\">\n"
                    + "                    <div class=\"navbar-item\">\n"
                    + "                        <div class=\"buttons\">\n"
                    + "                            <a href=\"registro\" class=\"button is-link\">\n"
                    + "                                <strong>Registro</strong>\n"
                    + "                            </a>\n"
                    + "                            <a href=\"login\"class=\"button is-light\">\n"
                    + "                                Iniciar Sesión\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div>\n"
                    + "            </div>\n"
                    + "        </nav>";

        } else {
            usuario = " <nav class=\"navbar\" role=\"navigation\" aria-label=\"main navigation\">\n"
                    + "            <div class=\"navbar-brand\">\n"
                    + "                <a class=\"navbar-item\" href=\"panel\">\n"
                    + "                    <img src=\"https://bulma.io/images/bulma-logo.png\" width=\"112\" height=\"28\">\n"
                    + "                </a>\n"
                    + "\n"
                    + "                <a role=\"button\" class=\"navbar-burger burger\" aria-label=\"menu\" aria-expanded=\"false\" data-target=\"navbarBasicExample\">\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                    <span aria-hidden=\"true\"></span>\n"
                    + "                </a>\n"
                    + "            </div>\n"
                    + "\n"
                    + "            <div id=\"navbarBasicExample\" class=\"navbar-menu\">\n"
                    + "                <div class=\"navbar-start\">\n"
                    + "                    <a class=\"navbar-item\" href=\"panel\">\n"
                    + "                        Inicio\n"
                    + "                    </a>\n"
                    + "\n"
                    + "\n"
                    + ""
                    + "<div class=\"navbar-item\">\n"
                    + "<form method='GET' action='busqueda'>"
                    + "  <div class=\"control\">\n"
                    + "    <input name='search' id='search' class=\"input\" type=\"text\" placeholder=\"Buscar usuario\">\n"
                    + "  </div>\n"
                    + "</div>"
                    + " <div class=\"field has-addons navbar-item\">\n"
                    + "    <button type='submit' class=\"button is-rounded is-info\">\n"
                    + "      Buscar\n"
                    + "  </div>\n"
                    + "</div>"
                    + "</form>"
                    + "</div>"
                    + "                </div>\n"
                    + "\n"
                    + "                <div class=\"navbar-end\">\n"
                    + "                    <div class=\"navbar-item\">\n"
                    + "                        <div class=\"buttons\">\n"
                    + "                    <div class=\"navbar-item has-dropdown is-hoverable\">\n"
                    + "                        <a class=\"navbar-link\">\n"
                    + "                            @" + nombre + "\n"
                    + "                        </a>\n"
                    + "\n"
                    + "                        <div class=\"navbar-dropdown\">\n"
                    + "                            <a href='perfil' class=\"navbar-item\">\n"
                    + "                                Perfil\n"
                    + "                            </a>\n"
                    + "                             <a href='logout' class=\"navbar-item\">\n"
                    + "                                Cerrar Sesión\n"
                    + "                            </a>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "                </div>\n"
                    + "            </div>\n"
                    + "        </nav>";
        }
        return usuario;

    }
}
